### ISSUE TITLE
CVNSimpleOverlay dosen't update

### ISSUE THREAD

**Issue by TomymyFr** [countervandalism/mw-gadget-cvnoverlay#3]
Hi, i'm [Tomybrz](https://fr.wikipedia.org/wiki/User:Tomybrz) from fr.wikipedia. Since the beginning of september, i see [CVNSimpleOverlay](https://meta.wikimedia.org/wiki/User:Krinkle/Scripts/CVNSimpleOverlay_wiki.js) dosen't update. More precisely :

Yesterday i connected in #cvn-sw and i put in the tchat this command (Nb: I'm voiced) : 
`CVNBot6 bl add Neutralisator1 x=0 r=Abusing multiples accounts.`
10min -> 2 hours next, nothing. To see if i'm only one with the problem, i tell other one on fr.wikipedia to install this gagdget : same problem ; nothing update : ![Image](https://screenshotscdn.firefoxusercontent.com/images/02179341-7950-4ae4-88e6-0d0a6207881a.png) but listed in #cvn-sw. 

I go to #countervandalism and they tell me : "it's normal, that can take few hours to update". I knew i put a other people in the blacklist for crosswiki vandalism few days ago (now globalyblocked) and i just verify if he's in the blacklist : same problem (Message : unlisted).

I took a break from june to early september (because exams, familly, ect..) and the gadget worked before. I checked my script (with a other account [TomyTest](https://fr.wikipedia.org/wiki/User:TomyTest) and i don't know what is the exact cause of this problem. (and sorry for sometimes my english is bad)
Regards 

Ps : after i wrote this issues in meta. I made a second try :
`CVNBot6 wl add Trizek (WMF) x=0 r=Staff`

Same problem : ![Image](https://screenshotscdn.firefoxusercontent.com/images/05778bfd-5a92-4d5a-aff5-4d7e56fbb4a0.png) 

Regards

**Comment by Krinkle** [comment]
Hi @TomymyFr,

The CVNSimpleOverlay gets its data from CVNBot14, which is synchronised every 5 minutes to an API for wiki gadgets, at <https://cvn.wmflabs.org/api.php?users=Example>. There, I see that the last synchronisation was `"lastUpdate":1538422575`, which is an Epoch timestamp that translates to `01 Oct 2018 19:36 UTC`. This means the synchronisation is working.

CVNBot14 in turn gets its data synchronised from all CVN bots, including CVNBot6. That synchronisation is in real-time and happens in a hidden channel (`#cvn-broadcast`) where the robots talk to each other to synchronise changes to the whitelist and blacklist etc.

I found that the problem was that CVNBot6 was no longer in the broadcast channel after a Freenode netsplit. I have restarted the bot and it is now able to share its updates with CVNBot14 again.

I have run `CVNBot6 bl add Neutralisator1 x=0 r=Abusing multiples accounts` and found that now, within 3 minutes, it is also seen on wikis via CVNSimpleOverlay.

Thanks for reporting this issue!
